theme: jekyll-theme-cayman
title: Power Platform Challenge
show_downloads: true

baseurl: "/home" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://miguelverweij.github.io" # change this to the base hostname & protocol for your site

google_analytics: G-EQZ46DM4NN

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: miguelverweij
twitter:
  username: miguelverweij

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow
header_page_refs: ['Challenges', 'Discussions', 'Other']