title: Power Platform Challenge
description: Improve your low-code skills by executing fun challenges
show_downloads: false

baseurl: ""  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://www.powerplatformchallenge.com" # change this to the base hostname & protocol for your site


google_analytics: G-EQZ46DM4NN

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # jekyll-theme-cayman-blog 

# social
author: miguelverweij
image: /thumbnail-jumbo.png
twitter:
  username: miguelverweij
linkedin:
  username: miguel-verweij
buymeacoffee:
  username: miguelverweij

plugins:
  - jekyll-target-blank
  - jekyll-seo-tag

target-blank:
    rel: nofollow

header_page_refs: ['challenges', 'discussions' , 'about']
